on: [push, pull_request, workflow_dispatch]

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: |
          export FRIDA_VERSION=$(cat FRIDA_VERSION)
          cd frida-gum-sys && wget https://github.com/frida/frida/releases/download/$FRIDA_VERSION/frida-gum-devkit-$FRIDA_VERSION-linux-x86_64.tar.xz -O frida-gum.tar.xz && tar xJvf frida-gum.tar.xz
          cd ..
          cd frida-sys && wget https://github.com/frida/frida/releases/download/$FRIDA_VERSION/frida-core-devkit-$FRIDA_VERSION-linux-x86_64.tar.xz -O frida-core.tar.xz && tar xJvf frida-core.tar.xz
      - run: rustup component add rustfmt clippy
      - uses: actions-rs/cargo@v1
        with:
          command: check
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  test-gum:
    name: Test Gum
    strategy:
      matrix:
          os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Test Gum
        run: cd frida-gum && cargo test --features=auto-download
      - name: Test Gum with all features
        run: cd frida-gum && cargo test --all-features
  test-frida:
    name: Test Frida
    strategy:
      matrix:
          os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Test Frida
        run: cd frida && cargo test --features=auto-download
      - name: Test Frida with all features
        run: cd frida && cargo test --all-features
  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    env:
      DOCS_RS: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Build Gum documentation
        run: |
          cd frida-gum
          cargo rustdoc --features "event-sink invocation-listener" -- --cfg doc_cfg
